# Generated by Django 3.2.5 on 2021-11-02 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttime',
            name='sequence',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cuttime',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animate1', to='animateapp.cropani'),
        ),
        migrations.AlterField(
            model_name='cuttime',
            name='length',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RenameModel(
            old_name='CropAni',
            new_name='Crop_cut',
        ),
        migrations.CreateModel(
            name='Animate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.FileField(null=True, upload_to='article/ani/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'mkv', 'mpeg', 'webm'])])),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animate0', to='animateapp.crop_cut')),
            ],
        ),
    ]
