# Generated by Django 3.2.5 on 2021-11-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0002_auto_20211103_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttime',
            name='image',
        ),
        migrations.AlterField(
            model_name='animate',
            name='image',
            field=models.ImageField(null=True, upload_to='animate/'),
        ),
        migrations.DeleteModel(
            name='Crop_cut',
        ),
        migrations.DeleteModel(
            name='CutTime',
        ),
    ]
