# Generated by Django 3.2.5 on 2021-11-03 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0006_alter_animate_ani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='ani',
            field=models.FileField(blank=True, null=True, upload_to='ani/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'mkv', 'mpeg', 'webm'])]),
        ),
    ]
