# Generated by Django 3.2.5 on 2021-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0007_alter_animate_ani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animate',
            name='ani',
        ),
        migrations.AddField(
            model_name='animate',
            name='ani_path',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
