# Generated by Django 3.2.5 on 2021-11-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0010_auto_20211105_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animate',
            name='ani1',
        ),
        migrations.RemoveField(
            model_name='animate',
            name='ani2',
        ),
        migrations.RemoveField(
            model_name='animate',
            name='ani3',
        ),
    ]
