# Generated by Django 3.2.5 on 2021-11-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0012_animate_ani1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animate',
            name='ani1',
        ),
    ]
