# Generated by Django 3.2.5 on 2021-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0013_remove_animate_ani1'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='left_right',
            field=models.CharField(choices=[('좌', '좌->우'), ('우', '우->좌')], default='좌', max_length=5),
        ),
    ]
